# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Publish Docker Image

on:
  push:
    branches:
      - '**'
    tags:
      - 'v*.*.*'
  # pull_request:
  #   branches:
  #     - 'master'

jobs:
  push_to_registries:
    name: Push Docker image to multiple registries
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      -
        name: Check out the repo
        uses: actions/checkout@v4

      -
        name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            blacktop/idapro
            ghcr.io/${{ github.repository }}

      -
        name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      -
        name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image (v7)
        id: docker_build_7
        uses: docker/build-push-action@v4
        with:
          context: ./7.7
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            blacktop/idapro:7
            blacktop/idapro:7.7
            ghcr.io/blacktop/idapro:7
            ghcr.io/blacktop/idapro:7.7
          labels: ${{ steps.meta.outputs.labels }}

      - name: Build and push Docker image (v8)
        id: docker_build_8
        uses: docker/build-push-action@v4
        with:
          context: ./8.2
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            blacktop/idapro:8
            blacktop/idapro:8.2
            blacktop/idapro:latest
            ghcr.io/blacktop/idapro:8
            ghcr.io/blacktop/idapro:8.2
            ghcr.io/blacktop/idapro:latest
          labels: ${{ steps.meta.outputs.labels }}

      # - name: Build and push Docker image (alpine)
      #   id: docker_build_alpine
      #   uses: docker/build-push-action@v4
      #   with:
      #     context: ./alpine
      #     push: ${{ github.event_name != 'pull_request' }}
      #     tags: |
      #       blacktop/idapro:7-alpine
      #       blacktop/idapro:7.7-alpine
      #       blacktop/idapro:alpine
      #       ghcr.io/blacktop/idapro:10-alpine
      #       ghcr.io/blacktop/idapro:10.1-alpine
      #       ghcr.io/blacktop/idapro:10.1.2-alpine
      #       ghcr.io/blacktop/idapro:alpine
      #     labels: ${{ steps.meta.outputs.labels }}
